model:
  arch: dpt_base

data:
  dataset: dsm
  train_split: training
  val_split: val
  img_rows: 240
  img_cols: 240
  path: /home/diego/cs4960R/SemSegSOTA/Datasets/dense_semantic_mapping/full_images

training:
  n_workers: 0
  train_iters: 20000
  batch_size: 1
  val_interval: 1000
  print_interval: 100
  optimizer:
    name: 'sgd'
    lr: 1.0e-5
    weight_decay: 0.0005
    momentum: 0.99
  lr_schedule:
    name: 'poly_lr'
    max_iter: 5
    gamma: 0.1
  loss: 
    name: 'cross_entropy'
    
  resume: dpt_base_dsm_best_model.pkl
