model:
  arch: segnet

data:
  dataset: dsm
  train_split: training
  val_split: val
  img_rows: 500
  img_cols: 500
  path: /home/diego/cs4960R/SemSegSOTA/Datasets/dense_semantic_mapping/full_images

training:
  n_workers: 0
  train_iters: 240000
  batch_size: 1
  val_interval: 1000
  print_interval: 100
  optimizer:
    name: 'sgd'
    lr: 1.0e-4
    weight_decay: 0.0005
    momentum: 0.99
  loss: 
    name: 'cross_entropy'
  lr_schedule:
  resume: segnet_dsm_best_model.pkl
